#!/usr/bin/env bash
set -euo pipefail

INSTALL_ROOT="${INSTALL_ROOT:-$HOME/Library/Application Support/ProtCross}"
PYTHON_BIN="${PYTHON_BIN:-python3.10}"
PROXY_URL="${PROXY_URL:-}"
UV_BIN="${UV_BIN:-}"
WHEELHOUSE="${WHEELHOUSE:-}"
ALLOW_ONLINE_PACKAGE_INDEX="${ALLOW_ONLINE_PACKAGE_INDEX:-0}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install-root)
      INSTALL_ROOT="$2"
      shift 2
      ;;
    --python)
      PYTHON_BIN="$2"
      shift 2
      ;;
    --proxy-url)
      PROXY_URL="$2"
      shift 2
      ;;
    --uv-bin)
      UV_BIN="$2"
      shift 2
      ;;
    --wheelhouse)
      WHEELHOUSE="$2"
      shift 2
      ;;
    --allow-online-package-index)
      ALLOW_ONLINE_PACKAGE_INDEX=1
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DESKTOP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_DIR="$INSTALL_ROOT/runtime/cpu-env"
PYTHON="$ENV_DIR/bin/python"
COMMON_REQUIREMENTS="$SCRIPT_DIR/requirements-common.lock"
BACKEND_HASH_REQUIREMENTS="$SCRIPT_DIR/requirements-cpu.hashes"
BACKEND_PACKAGE="$DESKTOP_DIR/backend"
WHEELHOUSE="${WHEELHOUSE:-$SCRIPT_DIR/wheelhouse}"

if [[ -n "$PROXY_URL" ]]; then
  export HTTP_PROXY="$PROXY_URL"
  export HTTPS_PROXY="$PROXY_URL"
fi

mkdir -p "$(dirname "$ENV_DIR")"

resolve_uv_bin() {
  RESOLVED_UV_BIN="${UV_BIN:-$SCRIPT_DIR/uv/uv}"
  if [[ ! -x "$RESOLVED_UV_BIN" ]]; then
    echo "A usable Python 3.10 environment with pip was not found, and no bundled uv executable is available." >&2
    echo "Release builds must ship a signed/hashed Python bootstrapper; development installs may pass --python or --uv-bin." >&2
    exit 1
  fi
}

bootstrap_uv() {
  resolve_uv_bin
  "$RESOLVED_UV_BIN" python install 3.10
  "$RESOLVED_UV_BIN" venv --seed --allow-existing --python 3.10 "$ENV_DIR"
}

environment_python_works() {
  [[ -x "$PYTHON" ]] && "$PYTHON" --version >/dev/null 2>&1
}

environment_pip_works() {
  environment_python_works && "$PYTHON" -m pip --version >/dev/null 2>&1
}

repair_environment_pip() {
  if environment_pip_works; then
    return
  fi
  echo "[warn] Backend environment is missing pip; attempting an in-place repair: $ENV_DIR" >&2
  "$PYTHON" -m ensurepip --upgrade >/dev/null 2>&1 || true
  if environment_pip_works; then
    return
  fi
  resolve_uv_bin
  "$RESOLVED_UV_BIN" venv --seed --allow-existing --python "$PYTHON" "$ENV_DIR"
  if ! environment_pip_works; then
    echo "Backend environment repair did not produce a working pip: $ENV_DIR" >&2
    exit 1
  fi
}

install_requirements() {
  if [[ -d "$WHEELHOUSE" && -f "$BACKEND_HASH_REQUIREMENTS" ]]; then
    "${PIP[@]}" install --no-index --find-links "$WHEELHOUSE" --require-hashes -r "$BACKEND_HASH_REQUIREMENTS"
    return
  fi
  if [[ "$ALLOW_ONLINE_PACKAGE_INDEX" == "1" ]]; then
    echo "[warn] Installing from online package indexes without hash verification; development use only." >&2
    "${PIP[@]}" install torch==2.3.1 torchvision==0.18.1
    "${PIP[@]}" install -r "$COMMON_REQUIREMENTS"
    "${PIP[@]}" install "$BACKEND_PACKAGE"
    return
  fi
  echo "Missing hash-locked desktop wheelhouse: $WHEELHOUSE" >&2
  echo "Release installs require requirements-cpu.hashes generated by prepare_runtime_wheelhouse.py." >&2
  exit 1
}

if ! environment_python_works; then
  if command -v "$PYTHON_BIN" >/dev/null 2>&1; then
    if ! "$PYTHON_BIN" -m venv "$ENV_DIR"; then
      echo "[warn] System Python could not create a complete environment; falling back to bundled uv." >&2
      bootstrap_uv
    fi
  else
    bootstrap_uv
  fi
fi

repair_environment_pip
PIP=("$PYTHON" -m pip)

install_requirements

echo "ProtCross CPU backend installed at $ENV_DIR"
