param(
  [string]$InstallRoot = "$env:LOCALAPPDATA\ProtCross",
  [string]$PythonExe = "py",
  [string[]]$PythonArgs = @("-3.10"),
  [string]$ProxyUrl = "",
  [string]$UvExe = "",
  [string]$Wheelhouse = "",
  [switch]$AllowOnlinePackageIndex
)

$ErrorActionPreference = "Stop"
$RuntimeDir = Join-Path $InstallRoot "runtime"
$EnvDir = Join-Path $RuntimeDir "cpu-env"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$CommonRequirements = Join-Path $ScriptDir "requirements-common.lock"
$BackendHashRequirements = Join-Path $ScriptDir "requirements-cpu.hashes"
$BackendPackage = Join-Path (Split-Path -Parent $ScriptDir) "backend"
if ($Wheelhouse -eq "") {
  $Wheelhouse = Join-Path $ScriptDir "wheelhouse"
}

New-Item -ItemType Directory -Force -Path $RuntimeDir | Out-Null

if ($ProxyUrl -ne "") {
  $env:HTTP_PROXY = $ProxyUrl
  $env:HTTPS_PROXY = $ProxyUrl
}

function Invoke-Checked {
  param(
    [Parameter(Mandatory = $true)][string]$FilePath,
    [Parameter(Mandatory = $true)][string[]]$Arguments
  )
  & $FilePath @Arguments
  if ($LASTEXITCODE -ne 0) {
    throw "Command failed with exit code ${LASTEXITCODE}: $FilePath $($Arguments -join ' ')"
  }
}

function Test-PythonCommand {
  try {
    & $PythonExe @PythonArgs --version *> $null
    return $LASTEXITCODE -eq 0
  } catch {
    return $false
  }
}

function Get-UvExe {
  $Candidate = $UvExe
  if ($Candidate -eq "") {
    $Candidate = Join-Path $ScriptDir "uv\uv.exe"
  }
  if (!(Test-Path $Candidate)) {
    throw "Python 3.10 was not found and no bundled uv executable is available. Release builds must ship a signed/hashed Python bootstrapper; development installs may pass -PythonExe."
  }
  return $Candidate
}

function Install-Requirements {
  if ((Test-Path $Wheelhouse) -and (Test-Path $BackendHashRequirements)) {
    Invoke-Checked $Pip @("install", "--no-index", "--find-links", $Wheelhouse, "--require-hashes", "-r", $BackendHashRequirements)
    return
  }
  if ($AllowOnlinePackageIndex) {
    Write-Warning "Installing from online package indexes without hash verification; development use only."
    Invoke-Checked $Pip @("install", "torch==2.3.1+cpu", "torchvision==0.18.1+cpu", "--index-url", "https://download.pytorch.org/whl/cpu")
    Invoke-Checked $Pip @("install", "-r", $CommonRequirements)
    Invoke-Checked $Pip @("install", $BackendPackage)
    return
  }
  throw "Missing hash-locked desktop wheelhouse: $Wheelhouse. Release installs require requirements-cpu.hashes generated by prepare_runtime_wheelhouse.py."
}

if (!(Test-Path $EnvDir)) {
  if (Test-PythonCommand) {
    Invoke-Checked $PythonExe ($PythonArgs + @("-m", "venv", $EnvDir))
  } else {
    $UvExe = Get-UvExe
    Invoke-Checked $UvExe @("python", "install", "3.10")
    Invoke-Checked $UvExe @("venv", "--python", "3.10", $EnvDir)
  }
}

$Pip = Join-Path $EnvDir "Scripts\pip.exe"
$Python = Join-Path $EnvDir "Scripts\python.exe"

Install-Requirements

Write-Host "ProtCross CPU backend installed at $EnvDir"
