"""Command line interface for lightweight ProtCross prediction."""

from __future__ import annotations

import argparse
import math
import os
import re
import sys
import tempfile
from pathlib import Path

from protcross.assets import ESM_LICENSE_URL


MAX_ESM_RESIDUES = 1022


def build_parser(prog: str | None = None) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog=prog,
        description="Predict binding-site model scores for one PDB/mmCIF structure and write them to B-factors.",
        epilog=(
            "Recommended preflight: protcross inspect INPUT\n"
            "First managed setup downloads about 2.14 GiB of ESM-C weights and resumes retained .part files.\n"
            f"ESM-C license: {ESM_LICENSE_URL}"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("input_pdb", nargs="?", help="Input PDB/mmCIF structure.")
    parser.add_argument("--pdb_file", "--pdb-file", dest="pdb_file", help="Legacy input structure argument.")
    parser.add_argument(
        "--assets-dir",
        help=(
            "Directory containing a ProtCross checkpoint, esmc_600m_2024_12_v0.pth, "
            "and a matching PCA reducer. Explicit file arguments override this."
        ),
    )
    parser.add_argument(
        "--checkpoint",
        "--ckpt-path",
        "--ckpt_path",
        dest="ckpt_path",
        default=os.environ.get("PROTCROSS_CHECKPOINT"),
        help=(
            "ProtCross Lightning checkpoint. Defaults to PROTCROSS_CHECKPOINT, "
            "installed assets, or the selected asset bundle cache."
        ),
    )
    parser.add_argument(
        "--esm-weights",
        "--esm_weights",
        dest="esm_weights",
        default=os.environ.get("PROTCROSS_ESM_WEIGHTS"),
        help="Local ESM-C 600M weights. Can also be set with PROTCROSS_ESM_WEIGHTS.",
    )
    parser.add_argument(
        "--pca",
        "--pca-path",
        "--pca_path",
        dest="pca_path",
        default=os.environ.get("PROTCROSS_PCA"),
        help=(
            "Fitted PCA pickle for ESM-C embeddings. Defaults to PROTCROSS_PCA, "
            "installed assets, or the selected asset bundle cache."
        ),
    )
    parser.add_argument(
        "-o",
        "--output",
        "--output_pdb",
        "--output-pdb",
        dest="output_pdb",
        help=(
            "Annotated structure path. Defaults beside the input (or in --out-dir) to "
            "INPUT.protcross.pdb/.cif; the format must match the input."
        ),
    )
    parser.add_argument(
        "--out-dir",
        "--output-dir",
        dest="out_dir",
        help="Directory for the four default result files; defaults to the input directory.",
    )
    parser.add_argument("--scores-tsv", help="Residue score table path; generated by default.")
    parser.add_argument("--pocket-json", help="Cluster/pocket JSON path; generated by default.")
    parser.add_argument("--summary-json", help="Run summary JSON path; generated by default.")
    parser.add_argument(
        "--pocket-cluster-cutoff",
        type=_positive_float,
        default=8.0,
        help="CA-CA single-linkage cutoff in Angstroms for predicted-residue clusters (default: 8.0).",
    )
    parser.add_argument(
        "--threshold",
        type=_probability_threshold,
        default=0.5,
        help=(
            "Threshold for binary calls, TSV is_binding, residue selection, clustering, "
            "and terminal summary. Default 0.5 is not independently calibrated; B-factors retain continuous scores."
        ),
    )
    parser.add_argument("--chain", "--chain-id", dest="chain_id", help="Restrict prediction to one chain.")
    parser.add_argument(
        "--device",
        default="cpu",
        type=_device_name,
        help="Compute device: cpu (default), auto (CUDA, then Apple MPS, then CPU), mps, cuda, or cuda:N.",
    )
    parser.add_argument(
        "--pca-dim",
        "--pca_dim",
        dest="pca_dim",
        type=_positive_int,
        default=128,
        help="Expected PCA output dimension; must match the reducer and checkpoint (default: 128).",
    )
    parser.add_argument(
        "--max-len",
        type=_max_len,
        default=MAX_ESM_RESIDUES,
        help=f"Maximum per-chain residues passed to ESM-C (default: {MAX_ESM_RESIDUES}).",
    )
    parser.add_argument(
        "--embedding-cache-dir",
        help="Optional directory for cached reduced ESM/PCA residue features keyed by sequence and asset metadata.",
    )
    parser.add_argument(
        "--asset-version",
        default=None,
        choices=("default", "latest", "0.1.2", "0.1.1-paper"),
        help=(
            "Asset bundle version. Defaults to PROTCROSS_ASSET_VERSION when set, "
            "otherwise the current 0.1.2 bundle."
        ),
    )
    parser.add_argument(
        "--refresh-assets",
        action="store_true",
        help="Re-download and verify managed assets; incompatible with --offline/--no-auto-assets.",
    )
    parser.add_argument(
        "--accept-esm-license",
        action="store_true",
        help="Confirm that you reviewed the ESM-C license; managed asset manifests record acceptance for later runs.",
    )
    parser.add_argument(
        "--trust-unverified-assets",
        action="store_true",
        help="Allow explicit local checkpoint/PCA/ESM files whose SHA256 does not match the selected release bundle.",
    )
    parser.add_argument(
        "--no-auto-assets",
        dest="auto_assets",
        action="store_false",
        help="Do not automatically download missing default prediction assets.",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Disable network asset setup and refresh for this prediction.",
    )
    parser.set_defaults(auto_assets=True)
    parser.add_argument(
        "--allow-truncation",
        action="store_true",
        help="For each over-limit chain, score only its leading --max-len scorable residues.",
    )
    parser.add_argument("--fail-on-truncation", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument(
        "--unscored-bfactor-policy",
        choices=("keep", "zero"),
        default="zero",
        help=(
            "How to write B-factors for unscored atoms/residues in the annotated structure. "
            "Default zero keeps the B-factor column in ProtCross model-score units; use keep "
            "to preserve original B-factors/pLDDT for unscored atoms."
        ),
    )
    parser.add_argument("--summary-only", action="store_true", help="Print the summary without creating default output files.")
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace existing result files. By default ProtCross refuses to overwrite them.",
    )
    parser.add_argument("--quiet", action="store_true")
    return parser


def main(argv: list[str] | None = None, *, prog: str | None = None) -> int:
    parser = build_parser(prog=prog)
    args = parser.parse_args(argv)

    input_pdb = args.input_pdb or args.pdb_file
    if not input_pdb:
        parser.error("an input PDB/mmCIF path is required")
    if args.offline and args.refresh_assets:
        parser.error("--offline cannot be combined with --refresh-assets")
    if not args.auto_assets and args.refresh_assets:
        parser.error("--no-auto-assets cannot be combined with --refresh-assets")
    if args.fail_on_truncation and args.allow_truncation:
        parser.error("--fail-on-truncation cannot be combined with --allow-truncation")
    input_path = Path(input_pdb).expanduser()
    if not input_path.exists():
        print(f"ProtCross prediction failed: Input structure not found: {input_path}", file=sys.stderr)
        return 1
    if input_path.suffix.lower() not in {".pdb", ".cif", ".mmcif"}:
        print(
            f"ProtCross prediction failed: Unsupported input structure extension: {input_path.suffix or '<none>'}",
            file=sys.stderr,
        )
        return 1
    try:
        inspection = _preflight_structure(
            input_path,
            chain_id=args.chain_id,
            max_len=args.max_len,
            allow_truncation=args.allow_truncation,
        )
    except Exception as exc:
        print(f"ProtCross prediction failed: {exc}", file=sys.stderr)
        return 1

    if not args.summary_only:
        output_paths = _default_output_paths(input_path, args.out_dir)
        args.output_pdb = args.output_pdb or str(output_paths["structure"])
        args.scores_tsv = args.scores_tsv or str(output_paths["scores_tsv"])
        args.pocket_json = args.pocket_json or str(output_paths["pockets_json"])
        args.summary_json = args.summary_json or str(output_paths["summary_json"])
    for attribute in ("output_pdb", "scores_tsv", "pocket_json", "summary_json"):
        value = getattr(args, attribute)
        if value:
            setattr(args, attribute, str(Path(value).expanduser()))
    try:
        _preflight_outputs(
            [args.output_pdb, args.scores_tsv, args.pocket_json, args.summary_json],
            overwrite=args.overwrite,
            input_path=input_path,
        )
        _preflight_device(args.device)
    except Exception as exc:
        print(f"ProtCross prediction failed: {exc}", file=sys.stderr)
        return 1

    try:
        if not args.quiet:
            chains = ", ".join(_display_chain(value) for value in inspection["selected_chains"]) or "none"
            print(
                f"[1/4] Input ready: {inspection['scorable_residue_count']} residues across chain(s) {chains}.",
                file=sys.stderr,
            )
            for warning in inspection.get("warnings", []):
                print(f"WARNING: {warning}", file=sys.stderr)
            print("[2/4] Resolving verified runtime assets (the first ESM-C download is about 2.14 GiB)...", file=sys.stderr)
        auto_setup = args.auto_assets and not args.offline
        assets = _resolve_prediction_asset_paths(
            args,
            auto_setup=auto_setup,
        )

        from protcross.inference import ProtCrossPredictor

        if not args.quiet:
            print(f"[3/4] Loading ESM-C, PCA, and ProtCross on {args.device}...", file=sys.stderr)
        predictor = ProtCrossPredictor.from_files(
            ckpt_path=args.ckpt_path,
            esm_weights=args.esm_weights,
            pca_path=args.pca_path,
            device=args.device,
            pca_dim=args.pca_dim,
            max_len=args.max_len,
            asset_version=assets.asset_version,
            asset_metadata=assets.asset_metadata,
            embedding_cache_dir=args.embedding_cache_dir,
            accept_esm_license=True,
        )
        if not args.quiet:
            print("[4/4] Embedding residues, scoring, clustering, and writing results...", file=sys.stderr)
        result = predictor.predict(
            input_path,
            chain_id=args.chain_id,
            threshold=args.threshold,
            pocket_cluster_cutoff=args.pocket_cluster_cutoff,
            output_pdb=args.output_pdb,
            scores_tsv=args.scores_tsv,
            pocket_json=args.pocket_json,
            summary_json=args.summary_json,
            allow_truncation=args.allow_truncation,
            unscored_bfactor_policy=args.unscored_bfactor_policy,
            structure_inspection=inspection,
        )
    except Exception as exc:
        print(f"ProtCross prediction failed: {exc}", file=sys.stderr)
        return 1

    if not args.quiet:
        print(result.format_summary())

    return 0


def _resolve_prediction_asset_paths(args: argparse.Namespace, *, auto_setup: bool):
    from protcross.assets import resolve_prediction_assets

    resolved = resolve_prediction_assets(
        ckpt_path=args.ckpt_path,
        esm_weights=args.esm_weights,
        pca_path=args.pca_path,
        assets_dir=args.assets_dir,
        auto_setup_assets=auto_setup,
        asset_version=args.asset_version,
        refresh_assets=args.refresh_assets,
        offline=args.offline,
        accept_esm_license=args.accept_esm_license,
        require_esm_license_for_use=True,
        trust_unverified_assets=args.trust_unverified_assets,
    )
    args.ckpt_path = str(resolved.checkpoint)
    args.esm_weights = str(resolved.esm_weights)
    args.pca_path = str(resolved.pca)
    return resolved


def _default_output_paths(input_pdb: str | Path, out_dir: str | Path | None = None) -> dict[str, Path]:
    input_path = Path(input_pdb).expanduser()
    output_dir = Path(out_dir).expanduser() if out_dir else input_path.parent
    structure_suffix = ".cif" if input_path.suffix.lower() in {".cif", ".mmcif"} else ".pdb"
    stem = input_path.stem
    return {
        "structure": output_dir / f"{stem}.protcross{structure_suffix}",
        "scores_tsv": output_dir / f"{stem}.protcross.scores.tsv",
        "pockets_json": output_dir / f"{stem}.protcross.pockets.json",
        "summary_json": output_dir / f"{stem}.protcross.summary.json",
    }


def _probability_threshold(value: str) -> float:
    threshold = float(value)
    if not math.isfinite(threshold) or not 0.0 <= threshold <= 1.0:
        raise argparse.ArgumentTypeError("must be in [0, 1]")
    return threshold


def _display_chain(chain_id: str) -> str:
    return chain_id if chain_id.strip() else "<blank>"


def _positive_float(value: str) -> float:
    number = float(value)
    if not math.isfinite(number) or number <= 0:
        raise argparse.ArgumentTypeError("must be greater than 0")
    return number


def _positive_int(value: str) -> int:
    number = int(value)
    if number <= 0:
        raise argparse.ArgumentTypeError("must be greater than 0")
    return number


def _max_len(value: str) -> int:
    number = _positive_int(value)
    if number > MAX_ESM_RESIDUES:
        raise argparse.ArgumentTypeError(f"must be <= {MAX_ESM_RESIDUES} for ESM-C")
    return number


def _device_name(value: str) -> str:
    normalized = value.strip().lower()
    if normalized in {"auto", "cpu", "mps", "cuda"} or re.fullmatch(r"cuda:\d+", normalized):
        return normalized
    raise argparse.ArgumentTypeError("must be auto, cpu, mps, cuda, or cuda:N")


def _preflight_structure(
    input_path: Path,
    *,
    chain_id: str | None,
    max_len: int,
    allow_truncation: bool,
) -> dict:
    from protcross.data import inspect_structure

    inspection = inspect_structure(input_path, chain_id=chain_id, max_len=max_len)
    if inspection["requires_truncation"] and not allow_truncation:
        raise ValueError(
            f"Input has an ESM chain context of {inspection['longest_chain_context']} scored residues, "
            f"which exceeds --max-len={max_len}. "
            "Pass --allow-truncation to score only the leading residues of each long chain."
        )
    return inspection


def _preflight_outputs(
    paths: list[str | None],
    *,
    overwrite: bool,
    input_path: str | Path | None = None,
) -> None:
    output_paths = [Path(path).expanduser() for path in paths if path]
    if input_path is not None and paths and paths[0]:
        input_suffix = Path(input_path).expanduser().suffix.lower()
        output_suffix = Path(paths[0]).expanduser().suffix.lower()
        input_is_cif = input_suffix in {".cif", ".mmcif"}
        output_is_cif = output_suffix in {".cif", ".mmcif"}
        if input_is_cif != output_is_cif:
            raise ValueError(
                "Annotated structure output must use the same PDB or mmCIF format as the input."
            )
    resolved_outputs: dict[Path, Path] = {}
    for path in output_paths:
        if path.is_dir():
            raise IsADirectoryError(f"Result path is a directory, not a file: {path}.")
        resolved = path.resolve(strict=False)
        if resolved in resolved_outputs:
            raise ValueError(
                "Result paths must be distinct; "
                f"{resolved_outputs[resolved]} and {path} resolve to the same file."
            )
        resolved_outputs[resolved] = path
    if input_path is not None:
        resolved_input = Path(input_path).expanduser().resolve(strict=False)
        conflicting = resolved_outputs.get(resolved_input)
        if conflicting is not None:
            raise ValueError(
                f"Result path must not overwrite the input structure: {conflicting}."
            )
    if not overwrite:
        existing = [path for path in output_paths if path.exists()]
        if existing:
            names = ", ".join(str(path) for path in existing)
            raise FileExistsError(f"Result file(s) already exist: {names}. Use --overwrite or choose --out-dir.")
    for parent in {path.parent for path in output_paths}:
        parent.mkdir(parents=True, exist_ok=True)
        try:
            with tempfile.NamedTemporaryFile(prefix=".protcross-write-test-", dir=parent):
                pass
        except OSError as exc:
            raise PermissionError(f"Output directory is not writable: {parent}") from exc


def _preflight_device(device: str) -> None:
    """Reject unavailable explicit devices before any asset download starts."""
    if device in {"auto", "cpu"}:
        return
    try:
        import torch
    except ImportError as exc:
        raise RuntimeError(
            f"{device} was requested, but PyTorch is not installed in this environment."
        ) from exc
    if device == "mps":
        if not hasattr(torch.backends, "mps") or not torch.backends.mps.is_available():
            raise ValueError("MPS was requested but is unavailable; use --device cpu.")
        return
    if not torch.cuda.is_available():
        raise ValueError("CUDA was requested but torch.cuda.is_available() is false; use --device cpu.")
    if ":" in device:
        index = int(device.split(":", 1)[1])
        if index >= torch.cuda.device_count():
            raise ValueError(
                f"CUDA device {index} was requested, but only {torch.cuda.device_count()} device(s) are available."
            )


if __name__ == "__main__":
    raise SystemExit(main())
